package Model;

import java.io.Serializable;

public enum STATES implements Serializable {
    SIGN_IN , SIGN_UP , WRONG_PASSWORD ,
    USER_NOT_FOUND , REPETITIVE_USERNAME ,
    USER_SIGNED_UP , USER_SIGNED_IN , NO_REQUEST ,
    STARTED , READED , UNREAD , STARRED , NOT_STARRED ,
    SEND_MESSAGE , USER_EXISTS , USER_NOT_EXISTS ,
    NEW_MESSAGE , SENT_PAGE , INBOX_PAGE ,
    MAIN_PAGE , CONVERSATION_PAGE , REPLY,
    FORWARD ,
    CHANGE_FIRST_NAME , CHANGE_LAST_NAME ,
    CHANGE_PASSWORD , CHANGE_BORN ,
    CHANGE_PHONENUMBER , CHANGE_SEXUALITY ,
    CHANGE_PROFILE_IMAGE , SEARCH_BY_SUBJECT ,
    SEARCH_BY_EMAILADDRESS , MESSAGE_WITH_FILE ,
    MESSAGE_WITHOUT_FILE, TEMP_PM , NORMAL_MESSAGE ,
    FINALIZE ,
}
